#!/usr/bin/env python3
#
# Wrapper around the yt_dlp library interface to try and make a usable
# CLI viewer with local cache
#
# requires:
#   mkdir -p ~/r/upstream
#   cd ~/r/upstream
#   git clone https://github.com/yt-dlp/yt-dlp

from __future__ import unicode_literals

import datetime
import json
import os
import socket
import subprocess
import sys
import urllib.request

# Define where the look for the yt_dlp libraries.  I would have used
# site.addsitedir(), but it does an append, not an insert...
sys.path.insert(0, os.path.expanduser('~/r/upstream/yt-dlp'))

import yt_dlp # noqa


def calculate_geometry():
    if "WINDOWID" not in os.environ:
        return []

    sp = subprocess.run(
        ["xwininfo", "-id", os.environ["WINDOWID"], "-stats"],
        capture_output=True,
        encoding="utf8",
        check=True,
        text=True
    )

    x=None
    y=None
    w=None
    h=None
    c=0

    for line in sp.stdout.splitlines():
        if line.startswith("  Absolute upper-left X:"):
            x = int(line[26:])
            c += 1
        if line.startswith("  Absolute upper-left Y:"):
            y = int(line[26:])
            c += 1
        if line.startswith("  Width:"):
            w = int(line[9:])
            c += 1
        if line.startswith("  Height:"):
            h = int(line[10:])
            c += 1

    if c != 4:
        return []

    # FIXME: this adjustment is a hack, based on one laptop's fvwm config
    x = max(0, x - 5)
    y = max(0, y - 33)

    return ["-geometry", f"{w}x{h}+{x}+{y}"]


class LazyListEncoder(json.JSONEncoder):
    def default(self, o):
        return list(o)


def make_basename(info):
    """Given the json info, construct the output base filename"""

    bad = ' /[]*%"\':'
    bar = '_' * len(bad)
    trans = str.maketrans(bad, bar)

    title = info['title'].strip().translate(trans)
    id = info['id']

    title = title[:230-len(id)]
    return '-'.join([title, id])


def get_subs_url(info):
    """Given the json info, find the best url"""

    if 'requested_subtitles' not in info:
        return None

    if info['requested_subtitles'] is None:
        return None

    for subdef in info['requested_subtitles'].values():
        if subdef['ext'] == 'vtt':
            return subdef['url']

    return None


def get_subs(info):
    """Download the subtitles and return the string"""
    # TODO: returning the entire text could be a memory hog

    url = get_subs_url(info)
    if url is None:
        return None

    with urllib.request.urlopen(url) as response:
        subs = response.read()

    return subs


progress_data = {}


def progress_hook(d):
    if progress_data['triggered']:
        # we have already triggered the playback
        return

    total_bytes_estimate = d.get('total_bytes_estimate')

    downloaded_bytes = d.get('downloaded_bytes')
    if downloaded_bytes is None:
        downloaded_bytes = total_bytes_estimate
    if downloaded_bytes is None:
        downloaded_bytes = 1

    if total_bytes_estimate is None:
        # TODO: a better guess!
        total_bytes_estimate = -1

    eta = d.get('eta')
    if eta is None:
        eta = 600
    # TODO: a better guess for ETA

    elapsed = d.get('elapsed')
    if elapsed is None:
        now = datetime.datetime.now(datetime.timezone.utc)
        elapsed = (now - progress_data['start']).seconds

    # TODO: if not provided, actually measure our elapsed

    seconds_downloaded = downloaded_bytes / progress_data['bps']
    etp = eta - progress_data['duration']

    print(
        f"etp={etp}s eta={eta}s "
        f"got {seconds_downloaded:.2f}/{progress_data['duration']}s "
        f", {downloaded_bytes:.2f}/{total_bytes_estimate}b "
        f"bps={progress_data['bps']:.2f} ",
        end="",
        flush=True,
    )

    # Now apply some heuristics to determine when to trigger the playback

    triggered = False
    reason = None

    if eta < progress_data['duration']:
        # We want it to have finished downloading by the time we reach the
        # end of the playback
        reason = "Enough"
        triggered = True

    # these tests need better tuning, however they are here to stop
    # the case where some files cannot even start playback without enough
    # header bytes
    if seconds_downloaded < 3:
        reason = "need seconds"
        triggered = False

    if downloaded_bytes < 700000:
        reason = "need bytes"
        triggered = False

    if elapsed < 5:
        reason = "need elapsed"
        triggered = False

    if d['status'] == 'finished':
        reason = "Finished"
        triggered = True

    if reason:
        print(reason, end="")
    print("  \r", end="")

    if not triggered:
        return

    progress_data['triggered'] = True

    # Could attempt to reduce the race condition, but not close it, by
    # sending the filename back up to the main process

    # if 'tmpfilename' in d:
    #     filename = d['tmpfilename']
    # else:
    #     filename = d['filename']

    progress_data['w'].write(b'a')


def print_info(url, rootname):
    print("url=", url)
    print("file=", rootname)


def main():
    # TODO:
    # - argsparser
    # - older subprocess does not have "run" method

    if len(sys.argv) < 2:
        r = subprocess.run(['xclip', '-o'], capture_output=True, text=True)
        url = r.stdout
    else:
        url = sys.argv[1]
    url = url.strip(' ')
    format = '43/18/35/45/22/best'
    cachedir = os.path.expanduser('~/.youtube')
    logdir = os.path.expanduser('~/s/organizer/youtube/')

    # FIXME:
    # if not url:
    #   url=`xclip -o`

    if not os.path.exists(cachedir):
        os.makedirs(cachedir)

    if not os.path.exists(logdir):
        os.makedirs(logdir)

    logfile = os.path.join(logdir, 'youtube.log.' + socket.gethostname())

    ydl_opts = {
        'quiet': True,
        'writesubtitles': True,  # causes extrac_info to fetch subtitle info
        'subtitleslangs': ['en', 'en-GB', 'en-US', 'en-AU', 'en-NZ', 'en-GB'],
        'format': format,
        'youtube_include_dash_manifest': False,
        'consoletitle': True,
        'progress_hooks': [progress_hook],
    }

    # Sometimes, format is not available (raises DownloadError)
    # TODO: handle this?  optional different formats? etc?

    # TODO:
    # - retry sometimes works
    # - distingush different errors

    # TODO:
    # - dont download the subtitles until we know it is not a playlist

    retry = True
    while retry:
        try:
            ydl = yt_dlp.YoutubeDL(ydl_opts)
            info = ydl.extract_info(url, download=False)
        except yt_dlp.DownloadError as e:
            if e.args[0].endswith("requested format not available"):
                del ydl_opts["format"]
                del ydl_opts["youtube_include_dash_manifest"]
                retry = True
            else:
                print("DownloadError caught")
                exit(1)
        else:
            retry = False

    basename = make_basename(info)
    rootname = os.path.join(cachedir, basename)
    ext = info.get('ext', 'unknown')

    with open(rootname+'.info.json', 'w') as f:
        json.dump(
            info,
            f,
            indent=2,
            sort_keys=True,
            separators=(',', ': '),
            cls=LazyListEncoder,
        )

    _type = info.get('_type')
    if _type == 'playlist':
        print("Playlist:", info.get('title',''))
        for entry in info.get('entries'):
            print(entry.get('webpage_url'))
            print("   ", entry.get('title'))
        exit(1)

    subsname = rootname+'.vtt'
    subs = get_subs(info)
    if subs is not None:
        with open(subsname, 'wb') as f:
            f.write(subs)

    filesize = info.get('filesize', 2000000)
    duration = info.get('duration', 60)

    if filesize is None:
        # WTF?
        filesize = 2000000

    if duration == 0:
        duration = 60

    progress_data['filesize'] = filesize
    progress_data['duration'] = duration
    progress_data['bps'] = filesize / duration
    progress_data['triggered'] = False

    print_info(url, rootname)

    now = datetime.datetime.now(datetime.timezone.utc).astimezone()
    progress_data['start'] = now
    now = now.replace(microsecond=0)
    nowstr = now.isoformat()
    with open(logfile, 'a') as f:
        f.write("{} {} {}.{}\n".format(nowstr, url, basename, ext))

    outname = rootname + '.' + ext
    ydl.params.update({
        'outtmpl': {
            "default": outname,
        },
        'writesubtitles': False,  # we wrote them out above
    })

    # TODO:
    # - if file exists, perhaps we already have it downloaded ...
    # - if file.part exists, we are already downloading it ...

    r, w = os.pipe()
    r = os.fdopen(r, 'rb', 0)
    w = os.fdopen(w, 'wb', 0)

    pid = os.fork()
    if pid == 0:
        # child
        r.close()
        progress_data['w'] = w
        try:
            ydl.process_info(info)
        except AssertionError as e:
            # tell parent to quit
            progress_data['w'].write(b'e')
            raise(e)
        except yt_dlp.utils.DownloadError as e:
            # tell parent to quit
            progress_data['w'].write(b'e')
            raise(e)
            # TODO:
            # yt_dlp.utils.DownloadError: ERROR: unable to download video data: <urlopen error [Errno 101] Network is unreachable>
            # could be recoverable by retries

        except urllib.error.HTTPError as e:
            # tell parent to quit
            # TODO: A retry often works after a "HTTP Error 403: Forbidden"
            progress_data['w'].write(b'e')
            raise(e)

        exit(0)

    # parent
    w.close()

    # Wait on trigger byte
    c = r.read(1).decode('utf-8')
    if c is None:
        print("Got EOF on pipe")

    if c == 'e':
        print("Child sent us an error indicator")
        exit(1)

    if c != 'a':
        print("Child sent Unexpected '" + c + "' on pipe")

    if os.path.exists(outname):
        filename = outname
    else:
        # FIXME - race condition with file completing..
        filename = outname + '.part'

    if 'KODI' in os.environ:
        # TODO: have a better detection for this situation

        args = ['kodictl', "open"]
        args += [filename]

        r = subprocess.run(
            args,
            stdin=0,
            stdout=1,
            stderr=2,
        )
        print()
        print_info(url, rootname)
        returncode = r.returncode
    elif 'DISPLAY' in os.environ:
        # If we have no display, dont try to play it

        args = ['mplayer']
        args += ['-stop-xscreensaver']

        if "WINDOWID" in os.environ:
            args += calculate_geometry()

        if subs is not None:
            args += ['-sub', subsname]
        args += [filename]

        r = subprocess.run(
            args,
            stdin=0,
            stdout=1,
            stderr=2,
        )
        print_info(url, rootname)
        returncode = r.returncode
    else:
        returncode = 0

    exit(returncode)

    # FIXME:
    # - if download has not finished, we hang here, waiting


if __name__ == '__main__':
    main()
