#!/bin/bash

#
# Simple wrapper to allow simple watching of youtube videos
#

#
# TODO
# - store the URL somewhere (or make it easy to regenerate)
# - extract the Id from the URL param and look for a completed file without
#   hitting the internet (ls ~/.youtube/*$ID.*
#


DIR=~/.youtube
mkdir -p $DIR

LOGFILE=~/s/organizer/youtube/youtube.log.$(hostname)

if [ -z "$FORMAT" ]; then
    FORMAT=43/18/35/45/22/best
fi

if [ -x ~/tmp/src/youtube-dl/youtube-dl ]; then
	# use the newer version
	DL=~/tmp/src/youtube-dl/youtube-dl
elif [ -x ~/r/upstream/youtube-dl/youtube-dl ]; then
	DL=~/r/upstream/youtube-dl/youtube-dl
else
	DL=youtube-dl
fi

URL="$1"
if [ -z "$URL" ]; then
    echo need url
    exit 1
fi

TEMPLATE="%(title)s-%(id)s.%(ext)s"
BASENAME=$($DL -o $TEMPLATE --get-filename "$URL" |head -1 |tr " []%" "_")
# TODO - detect a multi-line response as a playlist and handle it appropriately
S=$?
if [ $S -ne 0 ]; then
	echo ERROR
	exit
fi 
if [ -z "$BASENAME" ]; then
    echo ERROR: null basename
    exit
fi
FILE=$DIR/$BASENAME



# Note this one down
mkdir -p "$(dirname "$LOGFILE")"
echo "$(date --rfc-3339=seconds) $URL $BASENAME" >>"$LOGFILE"

# #
# if [ -d ~/s/organizer/youtube/annex ]; then
# (
#     cd ~/s/organizer/youtube/annex
#     git annex addurl --relaxed --file "$BASENAME" "$URL"
# )
# fi

#-o "%(stitle)s-%(id)s.%(ext)s"
#	-o $FILE \
#-w -c

# TODO - replace this with something else
#	--max-quality=18 \
#        -f 18 \

$DL \
	--ignore-errors \
	--quiet \
	--console-title \
	-o "$FILE" \
	--continue \
        --format "$FORMAT" \
        --youtube-skip-dash-manifest \
        --write-info-json \
	"$URL" &

echo "Wait for file ${FILE}.part"
while [ ! -s "${FILE}.part" -a ! -s "${FILE}" ]; do
	sleep 1
done

echo Wait for size
SIZE=$(stat -c %s "${FILE}.part")
if [ -z "$SIZE" ]; then
    SIZE=0
fi

# FIXME - should vary size based on percentage or bitstream rate
while [ "$SIZE" -lt 1000000 -a ! -e "${FILE}" ]; do
    sleep 1
    SIZE=$(stat -c %s "${FILE}.part")
done

# Race here between the *.part having the right size and finishing..

# TODO - pause playing music
mplayer "${FILE}"*
# TODO - unpause playing music

echo "$FILE"
